using System.IO;
using System.Text;

namespace Editor.App;

/// <summary>
/// Saves and loads Vim-compatible session files.
/// Format: a Vim script with :edit, :tabedit, and cursor position commands.
/// </summary>
public static class SessionManager
{
    /// <summary>
    /// Saves the current session to a file.
    /// </summary>
    /// <param name="filePath">Path to save the session file.</param>
    /// <param name="openFiles">List of (filePath, cursorLine, cursorCol) for each open file.</param>
    /// <param name="activeIndex">Index of the currently active file.</param>
    public static void Save(string filePath, IReadOnlyList<(string FilePath, int Line, int Col)> openFiles, int activeIndex)
    {
        var sb = new StringBuilder();
        sb.AppendLine("\" Vim session file — generated by Editor");
        sb.AppendLine("\" Source this file with: :source Session.vim");
        sb.AppendLine();

        if (openFiles.Count == 0)
        {
            sb.AppendLine("enew");
            File.WriteAllText(filePath, sb.ToString());
            return;
        }

        // Open first file with :edit, subsequent files with :tabedit
        for (int i = 0; i < openFiles.Count; i++)
        {
            var (fp, line, col) = openFiles[i];
            if (i == 0)
                sb.AppendLine($"edit {EscapePath(fp)}");
            else
                sb.AppendLine($"tabedit {EscapePath(fp)}");
            sb.AppendLine($"call cursor({line + 1}, {col + 1})");
        }

        // Switch to active tab
        if (activeIndex > 0 && activeIndex < openFiles.Count)
            sb.AppendLine($"tabnext {activeIndex + 1}");

        File.WriteAllText(filePath, sb.ToString());
    }

    /// <summary>
    /// Reads a session file and returns the list of commands to execute.
    /// Returns null if the file cannot be read.
    /// </summary>
    public static IReadOnlyList<SessionCommand>? Load(string filePath)
    {
        if (!File.Exists(filePath)) return null;

        var commands = new List<SessionCommand>();
        foreach (var rawLine in File.ReadLines(filePath))
        {
            var line = rawLine.Trim();
            if (line.StartsWith('"') || line.Length == 0) continue;

            if (line.StartsWith("edit ") || line.StartsWith("e "))
            {
                var path = line[(line.IndexOf(' ') + 1)..].Trim();
                commands.Add(new SessionCommand(SessionCommandType.OpenFile, path));
            }
            else if (line.StartsWith("tabedit ") || line.StartsWith("tabe "))
            {
                var path = line[(line.IndexOf(' ') + 1)..].Trim();
                commands.Add(new SessionCommand(SessionCommandType.OpenFileInTab, path));
            }
            else if (line.StartsWith("call cursor("))
            {
                // parse call cursor(line, col)
                var inner = line[12..].TrimEnd(')');
                var parts = inner.Split(',');
                if (parts.Length == 2 &&
                    int.TryParse(parts[0].Trim(), out int ln) &&
                    int.TryParse(parts[1].Trim(), out int col))
                {
                    commands.Add(new SessionCommand(SessionCommandType.SetCursor, null, ln - 1, col - 1));
                }
            }
            else if (line.StartsWith("tabnext ") || line.StartsWith("tabn "))
            {
                var rest = line[(line.IndexOf(' ') + 1)..].Trim();
                if (int.TryParse(rest, out int tabNum))
                    commands.Add(new SessionCommand(SessionCommandType.SwitchTab, null, tabNum - 1));
            }
        }
        return commands;
    }

    private static string EscapePath(string path) =>
        path.Contains(' ') ? $"\"{path}\"" : path;
}

public enum SessionCommandType { OpenFile, OpenFileInTab, SetCursor, SwitchTab }

public record SessionCommand(
    SessionCommandType Type,
    string? Path = null,
    int Line = 0,
    int Col = 0);
